//users
export const ADD_CURRENT_USER = "ADD_CURRENT_USER";
export const ADD_CURRENT_USER_SUCCESS = "ADD_CURRENT_USER_SUCCESS";
export const UPDATE_CURRENT_USER_SUCCESS = "UPDATE_CURRENT_USER_SUCCESS";

//api calls
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

//chat
export const FETCH_ROOMS = "FETCH_ROOMS";
export const LOAD_ROOMS_SUCCESS = "LOAD_ROOMS_SUCCESS";

export const FETCH_ROOM_DETAILS = "FETCH_ROOM_DETAILS";
export const LOAD_ROOM_DETAILS_SUCCESS = "LOAD_ROOM_DETAILS_SUCCESS";

export const FETCH_MESSAGES = "FETCH_MESSAGES";
export const LOAD_MESSAGES_SUCCESS = "LOAD_MESSAGES_SUCCESS";

export const REQUEST_POST_MESSAGE = "REQUEST_POST_MESSAGE";
export const POST_MESSAGE_SUCCESS = "POST_MESSAGE_SUCCESS";
